# permissions for end users to view charmedk8scontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: charmedk8scontrolplane-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-control-plane-provider-charmed-k8s
    app.kubernetes.io/part-of: cluster-api-control-plane-provider-charmed-k8s
    app.kubernetes.io/managed-by: kustomize
  name: charmedk8scontrolplane-viewer-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - charmedk8scontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - charmedk8scontrolplanes/status
  verbs:
  - get
