apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: JujuControlPlane
metadata:
  labels:
    app.kubernetes.io/name: jujucontrolplane
    app.kubernetes.io/instance: jujucontrolplane-sample
    app.kubernetes.io/part-of: cluster-api-control-plane-provider-juju
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-control-plane-provider-juju
  name: jujucontrolplane-sample
spec:
  # TODO(user): Add fields here
