
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: JujuMachineTemplate
metadata:
  name: jujumachinetemplate-controlplane
spec:
  template:
    spec:
      constraints: "cores=2,mem=8G,root-disk=16G"
---


apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: JujuControlPlane
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cluster-sample
    app.kubernetes.io/name: jujucontrolplane
    app.kubernetes.io/instance: jujucontrolplane-sample
    app.kubernetes.io/part-of: cluster-api-control-plane-provider-juju
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-control-plane-provider-juju
  name: jujucontrolplane-sample
spec:
  replicas: 3
  machineTemplate:
    kind: JujuMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: jujumachinetemplate-controlplane
  controlPlaneConfig:
    controlPlaneApplications:
      - kubernetes-control-plane
      - etcd
